version: "3"
services:
  static:
    build: .
    image: registry.gitlab.com/astron-sdc/narcis/narcis-frontend:${NARCIS_FRONTEND_VERSION:-latest}
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.narcis-frontend.entryPoints=websecure"
      - "traefik.http.routers.narcis-frontend.service=narcis-frontend"
      - "traefik.http.routers.narcis-frontend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/narcis/`)"
      - "traefik.http.services.narcis-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.narcis-frontend-redirect.entryPoints=websecure"
      - "traefik.http.routers.narcis-frontend-redirect.service=noop@internal"
      - "traefik.http.routers.narcis-frontend-redirect.middlewares=narcis-redirect@docker"
      - "traefik.http.routers.narcis-frontend-redirect.rule=Host(`${HOSTNAME}`) && Path(`/narcis`)"
      - "traefik.http.middlewares.narcis-redirect.redirectRegex.regex=^https://${HOSTNAME}/narcis$$"
      - "traefik.http.middlewares.narcis-redirect.redirectRegex.replacement=https://${HOSTNAME}/narcis/"
    networks:
      - traefik_proxy
    restart: always

networks:
  traefik_proxy:
    external: true
