FROM node:lts-slim as BUILD_STAGE

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:mainline
COPY --from=BUILD_STAGE /app/dist /usr/share/nginx/html/sdc-platform/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
